#pragma once

#include <ntddk.h>
#include <wdf.h>
#include <hidport.h>

EXTERN_C_START

DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD IsoEvtDeviceAdd;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL IsoEvtIoDeviceControl;
EVT_WDF_OBJECT_CONTEXT_CLEANUP IsoEvtDriverContextCleanup;

typedef struct _DEVICE_CONTEXT {
    UNICODE_STRING DeviceInstanceId;
    ULONG AssignedSessionId;
    BOOLEAN IsolationEnabled;
} DEVICE_CONTEXT, *PDEVICE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT, IsoGetDeviceContext);

#define FILE_DEVICE_ISO_INPUT 0x00008050
#define IOCTL_ISO_REGISTER_DEVICE CTL_CODE(FILE_DEVICE_ISO_INPUT, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ISO_SET_SESSION    CTL_CODE(FILE_DEVICE_ISO_INPUT, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ISO_GET_STATUS     CTL_CODE(FILE_DEVICE_ISO_INPUT, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ISO_ENABLE         CTL_CODE(FILE_DEVICE_ISO_INPUT, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ISO_DISABLE        CTL_CODE(FILE_DEVICE_ISO_INPUT, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _ISO_DEVICE_REGISTRATION {
    WCHAR DeviceInstanceId[260];
    ULONG DeviceType; // 1 = keyboard, 2 = mouse
} ISO_DEVICE_REGISTRATION, *PISO_DEVICE_REGISTRATION;

typedef struct _ISO_SESSION_ASSIGNMENT {
    WCHAR DeviceInstanceId[260];
    ULONG SessionId;
} ISO_SESSION_ASSIGNMENT, *PISO_SESSION_ASSIGNMENT;

typedef struct _ISO_DEVICE_STATUS {
    WCHAR DeviceInstanceId[260];
    ULONG SessionId;
    BOOLEAN IsolationEnabled;
} ISO_DEVICE_STATUS, *PISO_DEVICE_STATUS;

EXTERN_C_END
